version: "3"

services:
  php:
    build:
      context: .
      args:
        - BUILD_PHP_VERSION=8.2 # the php version you want to build
        - BUILD_TIMEZONE=Asia/Shanghai # the timezone you want to set
        - BUILD_EXTENSIONS=mysqli pdo_mysql gd zip bcmath @composer redis